package model;

// Generated 04-nov-2015 12:16:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int numDept;
	private String dnombre;
	private String ciudad;
	private Set empleados = new HashSet(0);

	public Departamento() {
	}

	public Departamento(int numDept) {
		this.numDept = numDept;
	}

	public Departamento(int numDept, String dnombre, String ciudad,
			Set empleados) {
		this.numDept = numDept;
		this.dnombre = dnombre;
		this.ciudad = ciudad;
		this.empleados = empleados;
	}

	public int getNumDept() {
		return this.numDept;
	}

	public void setNumDept(int numDept) {
		this.numDept = numDept;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
