package model;

// Generated 04-nov-2015 12:16:42 by Hibernate Tools 3.4.0.CR1

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int numEmp;
	private Departamento departamento;
	private String nombre;
	private Float salario;

	public Empleado() {
	}

	public Empleado(int numEmp) {
		this.numEmp = numEmp;
	}

	public Empleado(int numEmp, Departamento departamento, String nombre,
			Float salario) {
		this.numEmp = numEmp;
		this.departamento = departamento;
		this.nombre = nombre;
		this.salario = salario;
	}

	public int getNumEmp() {
		return this.numEmp;
	}

	public void setNumEmp(int numEmp) {
		this.numEmp = numEmp;
	}

	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getSalario() {
		return this.salario;
	}

	public void setSalario(Float salario) {
		this.salario = salario;
	}

}
